# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 292b52fa5befdc8cba85e2c026715da154f6646b542086db86460294f76521eb7ecd50c9f6acf978024e54a67f0384a0914f03b3f6280971a083495d682256c4

test:
  secret_key_base: bdf005576ad0ef8cf1062f92b28e805bcb598f4ec60abf53b0e086896bc0ecd9cb4b5506c7bb10a6cbfe553f8ba27c8d9bcbabc341cf91ee9d4866bb4067c47d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
